pipeline:
  name: pipeline_sample
  identifier: pipeline_sample
  projectIdentifier: Krishika_CD_Samples
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cust_stage
        identifier: cust_stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo hell
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
